# Configuracoes do Banco de Dados (PostgreSQL)
spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_cursos
spring.datasource.username=postgres
spring.datasource.password=Biozard5@1215

# Configuracoes JPA e Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# Porta do servidor
server.port=8080

# Swagger
springdoc.swagger-ui.path=/swagger-ui.html